name: financrr_api
description: Dart package which allows to communicate with the financrr REST API.
version: 0.12.0

environment:
  sdk: ^3.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5

dependencies:
  dio: ^5.4.3+1
  logging: ^1.2.0
