# Loco configuration file documentation

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: {{get_env(name="LOG_ENABLED", default=true)}}
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: {{get_env(name="LOG_LEVEL", default="debug")}}
  # Define the logging format. options: compact, pretty or json
  format: {{get_env(name="LOG_FORMAT", default="compact")}}
  # By default, the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace
  file_appender:
    enable: {{get_env(name="LOG_FILE_ENABLED", default=true)}}
    non_blocking: true
    level: {{get_env(name="LOG_LEVEL", default="debug")}}
    format: {{get_env(name="LOG_FORMAT", default="pretty")}}
    dir: {{get_env(name="LOG_DIR", default="./logs")}}
    rotation: {{get_env(name="LOG_ROTATION", default="daily")}}
    max_log_files: {{get_env(name="LOG_MAX_LOG_FILES", default="7")}}
    filename_suffix: log

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: {{get_env(name="PORT", default="8080")}}
  # The actual IP-Binding that is used by the server
  binding: {{get_env(name="BINDING", default="127.0.0.1")}}
  # The UI hostname or IP address that mailers will point to.
  host: {{get_env(name="EXTERNAL_HOST", default="http://localhost:8080")}}
  ident: ""
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    compression:
      enable: true
    timeout_request:
      enable: {{get_env(name="TIMEOUT_ENABLED", default="true")}}
      timeout: {{get_env(name="TIMEOUT_REQUEST", default="10000")}}

# Worker Configuration
workers:
  # specifies the worker mode. Options:
  #   - BackgroundQueue - Workers operate asynchronously in the background, processing queued.
  #   - ForegroundBlocking - Workers operate in the foreground and block until tasks are completed.
  #   - BackgroundAsync - Workers operate asynchronously in the background, processing tasks with async capabilities.
  mode: BackgroundQueue


# Queue Configuration
queue:
  kind: Postgres
  # Redis connection URI
  uri: {{get_env(name="DATABASE_URL")}}
  # Dangerously flush all data in Redis on startup. dangerous operation, make sure that you're using this flag only on dev environments or test mode
  dangerously_flush: false
  # Represents the number of tasks a worker can handle simultaneously.
  num_workers: {{get_env(name="NUM_WORKERS", default="10")}}

# Mailer Configuration.
mailer:
  # SMTP mailer configuration.
  smtp:
    # Enable/Disable smtp mailer.
    enable: {{get_env(name="SMTP_ENABLED", default="false")}}
    # SMTP server host. e.x localhost, smtp.gmail.com
    host: {{get_env(name="SMTP_HOST", default="localhost")}}
    # SMTP server port
    port: {{get_env(name="SMTP_PORT", default="1025")}}
    # Use secure connection (SSL/TLS).
    secure: {{get_env(name="SMTP_SECURE", default="false")}}
    auth:
      user: {{get_env(name="SMTP_USER", default="")}}
      password: {{get_env(name="SMTP_PASSWORD", default="")}}

# Database Configuration
database:
  # Database connection URI
  uri: {{get_env(name="DATABASE_URL")}}
  # When enabled, the sql query will be logged.
  enable_logging: false
  # Set the timeout duration when acquiring a connection.
  connect_timeout: {{get_env(name="DATABASE_CONNECT_TIMEOUT", default="500")}}
  # Set the idle duration before closing a connection.
  idle_timeout: {{get_env(name="DATABASE_IDLE_TIMEOUT", default="500")}}
  # Minimum number of connections for a pool.
  min_connections: {{get_env(name="DATABASE_MIN_CONNECTIONS", default="0")}}
  # Maximum number of connections for a pool.
  max_connections: {{get_env(name="DATABASE_MAX_CONNECTIONS", default="5")}}
  # Run migration up when application loaded
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you're using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you're using this flag only on dev environments or test mode
  dangerously_recreate: false

bank_data_linking:
  enabled: {{get_env(name="GO_CARDLESS_ENABLED", default=false)}}
  secret_id: {{get_env(name="GO_CARDLESS_SECRET_ID", default="")}}
  secret_key: {{get_env(name="GO_CARDLESS_SECRET_KEY", default="")}}
  redirect_url: {{get_env(name="GO_CARDLESS_REDIRECT_URL", default="")}}

opensearch:
  is_https: {{get_env(name="OPENSEARCH_IS_HTTPS", default="true")}}
  host: {{get_env(name="OPENSEARCH_HOST", default="127.0.0.1")}}
  port: {{get_env(name="OPENSEARCH_PORT", default="9200")}}
  username: {{get_env(name="OPENSEARCH_USER")}}
  password: {{get_env(name="OPENSEARCH_PASSWORD")}}
  disable_proxy: {{get_env(name="OPENSEARCH_DISABLE_PROXY", default="false")}}
  disable_cert_validation: {{get_env(name="OPENSEARCH_DISABLE_CERT_VALIDATION", default="false")}}

scheduler:
  jobs:
    sync_institutions:
      run: "SyncInstitutions"
      schedule: "every 24 hours"
      run_on_start: true
