[workspace]
members = [
    "entity",
    "migration",
    "backend"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Timon Klinkert <DenuxPlays@users.noreply.github.com>"]
description = "Your personal finance manager"
license = "AGPL-3"
repository = "https://github.com/financrr/backend"
homepage = "https://github.com/financrr/backend"
readme = "README.md"
edition = "2021"
rust-version = "1.78.0"

[workspace.lints.clippy]
# Restriction
absolute_paths = "warn"
unwrap_used = "warn"

# Pedantic
wildcard-imports = "deny"
cloned_instead_of_copied = "warn"
explicit_iter_loop = "warn"
unnecessary_wraps = "warn"
unused_self = "warn"

# Nursey
cognitive_complexity = "deny"
use_self = "warn"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.37.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time", "parking_lot"] }

# Serialization/Deserialization
serde = { version = "1.0.203", features = ["derive"] }

# ORM
sea-orm = { version = "1.0.0-rc.4", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "mock"] }

# Date/Time
time = { version = "0.3.36", features = ["serde-human-readable", "local-offset"] }

# Logging
tracing = "0.1.40"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.11.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc"
]
# Publish jobs to run in CI
pr-run-mode = "plan"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
