[workspace]
members = [
    "migration",
    "financrr_macros",
    "financrr_macros_impl"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[package]
name = "financrr"
version.workspace = true
edition.workspace = true
publish.workspace = true
default-run = "financrr-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.lints.rust]
# Forbid
unsafe_code = "forbid"
non_ascii_idents = "forbid"

[workspace.dependencies]
loco-rs = { version = "0.13.2", features = ["with-db", "cache_inmem"] }
financrr_macros = { path = "financrr_macros" }

[dependencies]
# Loco Framework
loco-rs = { workspace = true }
axum = "0.7.9"
async-trait = "0.1.83"

# Database and ORM
sea-orm = { version = "1.1.2", features = [
    "sqlx-sqlite",
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
migration = { path = "migration" }

# Async runtime and scheduler
tokio = { version = "1.42.0", default-features = false, features = [
    "rt-multi-thread",
    "parking_lot"
] }
tokio-cron-scheduler = { version = "0.13.0", features = ["signal"] }

# Serialization
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

# Utoipa / OpenApi
utoipa = { version = "5.3.0", features = [
    "axum_extras",
    "openapi_extensions",
    "yaml",
    "preserve_order",
    "preserve_path_order",
    "non_strict_integers",
    "chrono",
    "uuid",
] }
utoipa-scalar = { version = "0.2.0", features = ["axum"] }
utoipa-swagger-ui = { version = "8.1.0", features = ["axum", "debug-embed"] }
utoipauto = "0.2.0"

# Logging
tracing = "0.1.41"

# Time and UUID
chrono = { version = "0.4.39", features = ["clock"] }
uuid = { version = "1.11.0", features = ["v4"] }

# Flags
enumflags2 = { version = "0.7.10", features = ["std", "serde"] }

# Validation
validator = { version = "0.18.1" }

# Env loading
dotenvy = "0.15.7"

# Mimalloc for better performance (eg. Alpine)
mimalloc = "0.1.43"

# Derive and Error utils
thiserror = "2.0.6"
derive_more = { version = "1.0.0", features = ["display", "error"] }

# File utils
include_dir = "0.7.4"

# Code generation/custom macros
financrr_macros.workspace = true

[[bin]]
name = "financrr-cli"
path = "src/bin/main.rs"
required-features = []

[[bin]]
name = "tool"
path = "src/bin/tool.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = "3.2.0"
rstest = "0.23.0"
insta = { version = "1.41.1", features = ["redactions", "yaml", "filters"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"
