[package]
name = "migration"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
# SeaORM
sea-orm-migration = { version = "1.1.6", features = ["runtime-tokio-rustls"] }
