//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "external_bank_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub logo_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::budget_criteria_external_bank_accounts::Entity")]
    BudgetCriteriaExternalBankAccounts,
    #[sea_orm(has_many = "super::external_bank_account_ibans::Entity")]
    ExternalBankAccountIbans,
    #[sea_orm(
        belongs_to = "super::file_attachments::Entity",
        from = "Column::LogoId",
        to = "super::file_attachments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    FileAttachments,
    #[sea_orm(has_many = "super::transaction_parties::Entity")]
    TransactionParties,
}

impl Related<super::budget_criteria_external_bank_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetCriteriaExternalBankAccounts.def()
    }
}

impl Related<super::external_bank_account_ibans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalBankAccountIbans.def()
    }
}

impl Related<super::file_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAttachments.def()
    }
}

impl Related<super::transaction_parties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionParties.def()
    }
}

impl Related<super::budget_criteria::Entity> for Entity {
    fn to() -> RelationDef {
        super::budget_criteria_external_bank_accounts::Relation::BudgetCriteria.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::budget_criteria_external_bank_accounts::Relation::ExternalBankAccounts
                .def()
                .rev(),
        )
    }
}
