//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod bank_accounts;
pub mod categories;
pub mod currencies;
pub mod external_bank_institutions;
pub mod file_attachments;
pub mod fixtures;
pub mod go_cardless_enduser_agreements;
pub mod go_cardless_requisitions;
pub mod imported_bank_accounts;
pub mod instances;
pub mod opensearch_migrations;
pub mod pending_transactions;
pub mod recurring_transactions;
pub mod sessions;
pub mod taggings;
pub mod tags;
pub mod transaction_parties;
pub mod transaction_templates;
pub mod transactions;
pub mod user_permissions;
pub mod users;
