//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction_parties")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub bank_account_id: Option<i64>,
    pub external_bank_account_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bank_accounts::Entity",
        from = "Column::BankAccountId",
        to = "super::bank_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BankAccounts,
    #[sea_orm(
        belongs_to = "super::external_bank_accounts::Entity",
        from = "Column::ExternalBankAccountId",
        to = "super::external_bank_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExternalBankAccounts,
}

impl Related<super::bank_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BankAccounts.def()
    }
}

impl Related<super::external_bank_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalBankAccounts.def()
    }
}
