name: (Backend Rust) Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

# Set default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run installation script
        run: bash bin/install
      - name: Create Docker Compose override
        run: |
          cat > compose.override.yaml << EOF
          services:
            rust:
              user: "1000:1000"
              environment:
                - HOST_UID=1000
                - HOST_GID=1000
          EOF
      - name: Set up user permissions
        run: |
          sudo chown -R 1000:1000 ./
      - name: Start Docker Container
        run: docker compose up -d rust --build
      - name: Build
        run: bin/cargo build --release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run installation script
        run: bash bin/install
      - name: Create Docker Compose override
        run: |
          cat > compose.override.yaml << EOF
          services:
            rust:
              user: "1000:1000"
              environment:
                - HOST_UID=1000
                - HOST_GID=1000
          EOF
      - name: Set up user permissions
        run: |
          sudo chown -R 1000:1000 ./
      - name: Start Docker Container
        run: docker compose up -d --build
      - name: Build tests
        run: bin/cargo nextest run --workspace --no-run
      - name: Run tests
        run: bash bin/test
