name: (Backend) Rust checks (security, clippy, rustfmt)
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

# Set default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./backend
          ignore: RUSTSEC-2023-0071, RUSTSEC-2024-0370

  clippy:
    env:
      RUSTFLAGS: "-Dwarnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy

  formatting:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly Rust for formatting
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Run rustfmt check and annotate PR
        uses: clechasseur/rs-fmt-check@v2
        with:
          toolchain: nightly
          working-directory: ./backend
