name: (Backend Rust) E2E Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

# Set default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install project
        run: bash bin/install.bash
      - name: Set permissions
        run: sudo chmod -R 777 ./logs
      - name: Build test containers
        run: bash bin/hurl/build.bash
      - name: Run E2E tests
        run: bash bin/hurl/execute-cicd-tests.bash
