name: (Backend Rust) Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

# Set default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
      options: >-
        --user 1000:1000
        -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v4
      - name: Run installation script
        run: bash bin/install
      - name: Start Docker Container
        run: docker compose up -d --build
      - name: Build
        run: bin/cargo build --release

  test:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
      options: >-
        --user 1000:1000
        -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v4
      - name: Run installation script
        run: bash bin/install
      - name: Start Docker Container
        run: docker compose up -d --build
      - name: Build tests
        run: bin/cargo nextest run --workspace --no-run
      - name: Run tests
        run: bash bin/test
